//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//
#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     beltMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    liftToggle,           tServoStandard)

//*Includes*//
#pragma debuggerWindows("joystickGame");
#include "JoystickDriver.c" //Include file to "handle" the Bluetooth messages.
//#include "controlFunctions.h"

//*Constants*//
const int BUTTONX  			= 1;
const int BUTTONA 		  = 2;
const int BUTTONB       = 3;
const int BUTTONY  			= 4;
const int BUTTONLB 			= 5;
const int BUTTONRB 			= 6;
const int BUTTONLT 			= 7;
const int BUTTONRT 			= 8;


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	servo[liftToggle] = 140; //Initializes servo to start position
  return;
}

//*Functions*//
void moveServo()
{
	//Moves servo to down position if the a button is pressed
	if(joy1Btn(BUTTONA))
		{
			servo[liftToggle] = 240;
			wait1Msec(1);
		}

	//Moves servo to up position if the b button is pressed
		if(joy1Btn(BUTTONB))
		{
			servo[liftToggle] = 140;
			wait1Msec(1);
		}
}

void runConveyer()
{
	if(joy1Btn(BUTTONRB))
	{
		motor[beltMotor] = 10;
		wait1Msec(1);
	}
	else
	{
		motor[beltMotor] = 0;
		wait1Msec(1);
	}
}

void moveLift()
{
	//Moves the lift upwards
	if(joy1Btn(BUTTONRT))
	{
			motor(liftMotor) = 10;
			wait1Msec(1);
	}
	else
	{
		motor(liftMotor) = 0;
		wait1Msec(1);
	}
	//Moves the lift down
	if(joy1Btn(BUTTONLT))
	{
			motor(liftMotor) = -10;
			wait1Msec(1);
	}
	else
	{
		motor(liftMotor) = 0;
		wait1Msec(1);
	}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();   //Sets servos into

  waitForStart();   // Waits for start of tele-op phase

  while (true)
  {
  	//Updates joystick variables with data from joystick station
		getJoystickSettings( joystick );

		//Recieves joystick data from controllers then sets the motor's power equal to the value of the joystick.
 	  motor[ driveLeft ] 		= joystick.joy1_y2;
  	motor[ driveRight ] 		= joystick.joy1_y1;
  	runConveyer();
  	moveLift();
  	moveServo();

  }
}
