#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     ballShooter,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    goalServo,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
//#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
//#pragma config(Motor,  mtr_S1_C2_1,     beltMotor,     tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C2_2,     liftMotor,     tmotorTetrix, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*Includes*//
#pragma debuggerWindows("joystickGame");
#include "JoystickDriver.c" //Include file to "handle" the Bluetooth messages.

//*Controller Constants*//
const int BUTTONX  			= 1;
const int BUTTONA 		  = 2;
const int BUTTONB       = 3;
const int BUTTONY  			= 4;
const int BUTTONLB 			= 5;
const int BUTTONRB 			= 6;
const int BUTTONLT 			= 7;
const int BUTTONRT 			= 8;


//*Global Variables*//
float moveModifier			= 1;
bool shiftSlowMo 				= false;
bool shiftDirection			= false;
bool shiftGoal					= false;

//*Function Prototypes*//
void initializeRobot();
void moveRobot();
void toggleSlow();
void toggleDirection();
void toggleGoalMover();
void ballLauncher();
//void moveLift();
//void runConveyer();




//The main task will run the robot initialization and then will wait for the signal from FCS
//to begin and enter the continuous loop that recieves joystick values and executes functions
//with this data.
task main()
{
  initializeRobot();   //Sets servos into starting positions

  waitForStart();   // Waits for start of tele-op phase
  while ( true )
  {

  	//Updates joystick variables with data from joystick station
		getJoystickSettings( joystick );
		moveRobot();
		toggleSlow();
		toggleDirection();
		toggleGoalMover();
		ballLauncher();
  	//runConveyer();
  	//moveLift();
  	//moveServo();

  }
}
//*Functions*//

//Sets all values and servos prior to the start of the telop mode.
void initializeRobot()
{
	servo[goalServo] = 135; //Initializes servo to start position
}

//Recieves joystick data from controllers then modifies that value
//and sets the motor equal to the modified value.
void moveRobot()
{
	//Sanitize low values from the joysticks
	if(abs(joystick.joy1_y1) < 5 && abs(joystick.joy1_y2) < 5)
	{
		motor[driveLeft]	=	0;
		motor[driveRight]	=	0;
	}
	else
	{
		motor[driveLeft]	= joystick.joy1_y2 / moveModifier;
		motor[driveRight]	= joystick.joy1_y1 / moveModifier;
	}

}

void toggleSlow()
{
	if(joy1Btn(BUTTONA))
	{
		if(!shiftSlowMo && abs(moveModifier) == 1)
		{
			moveModifier *= 10;
		}

		else if(!shiftSlowMo && abs(moveModifier) > 1)
		{
			moveModifier /= 10;
		}
		shiftSlowMo = true;
	}
	else
	{
		shiftSlowMo = false;
	}
}

void toggleDirection()
{
	if(joy1Btn(BUTTONY))
	{
		if(!shiftDirection)
		{
			moveModifier *= -1;
		}
		shiftDirection = true;
	}
	else
	{
			shiftDirection = false;
	}
}

void toggleGoalMover()
{
	if(joy1Btn(BUTTONB))
	{
		int upPosition = 135;
		int downPosition = 250;

		if(!shiftGoal && ServoValue[goalServo] != downPosition)
		{
			servo[goalServo] = downPosition;
		}
		else if(!shiftGoal && ServoValue[goalServo] != upPosition)
		{
			servo[goalServo] = upPosition;
		}
		shiftGoal = true;
	}
	else
	{
		shiftGoal = false;
	}
}

void ballLauncher()
{
	if(joy1Btn(BUTTONX))
	{
		motor[ballShooter]	=	50;
	}
	else
	{
		motor[ballShooter]	=	0;
	}
}
/*
//
void moveServo()
{
	//Moves servo to down position if the a button is pressed
	if( joy1Btn( BUTTONA ) )
		{
			servo[ liftToggle ] = 250;
			wait1Msec(1);
		}

	//Moves servo to up position if the b button is pressed
		if( joy1Btn( BUTTONB ) )
		{
			servo[ liftToggle ] = 130;
			wait1Msec(1);
		}
}


void runConveyer()
{
	if( joy1Btn( BUTTONRB ) )
	{
		motor[ beltMotor ] = 15;
		wait1Msec(1);
	}
	else if ( joy1Btn( BUTTONLB ) )
  {
  	motor[ beltMotor ] = -15;
  	wait1Msec(1);
  }
	else
	{
		motor[ beltMotor ] = 0;
		wait1Msec(1);
	}
}

void moveLift()
{
	//Moves the lift upwards
	if( joy1Btn( BUTTONRT ) )
	{
			motor( liftMotor ) = 100;
			wait1Msec(10);
	}
	else
	{
		motor( liftMotor ) = 0;
		wait1Msec(10);
	}
	//Moves the lift down
	if( joy1Btn( BUTTONLT ) )
	{
			motor( liftMotor ) = -100;
			wait1Msec(10);
	}
	else
	{
		motor( liftMotor ) = 0;
		wait1Msec(10);
	}
}
*/

