//motors, sensors, and servos setup
#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBlock,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoAutonomousBucket, BadType)
#pragma config(Servo,  srvo_S2_C1_2,    FlagRaiser,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    Raiser,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Dillon & Chase & Will & Walsh & Derrick
//11/9/13
//TeleOp

////////////////////////////////////////////////////////////////////

#pragma debuggerWindows("joystickGame");
#include "JoystickDriver.c"

// Function headers
void moveServoArm();
void moveFlag();
//void moveBucketPosition();
void initializeRobot();
void moveLift();
// Constant variables for controller buttons
const int buttonX  			= 1;
//const int buttonA 		 = 2;
//const int buttonB          = 3;
const int buttonY  			= 4;
const int buttonLB 			= 5;
const int buttonRB 			= 6;
const int buttonLT 			= 7;
const int buttonRT 			= 8;

// Constant variables for rotation of robot
//const int bucketRotation = 40;
//const int MaxRotation   = 127;

int armRotation   		   = 255;

////////

task main()
{
	initializeRobot();
  waitForStart();

	while( true )
	{
  	getJoystickSettings( joystick );
 	  motor[ motorL ] 		= joystick.joy1_y2;
  	motor[ motorR ] 		= joystick.joy1_y1;


  	moveServoArm();
  	moveFlag();
  	moveLift();
	}
}

//Functions
///////////

// Move Main Arm Function
void moveServoArm()
{
	if( joy2Btn( buttonRT ) )                     //if right trigger is pressed
		armRotation --;                             //gradually lowers arm
 	else if( joy2Btn( buttonRB ) )                //if right bumper is pressed
  	armRotation ++;                             //gradually raises arm
 	servo[ servoAutonomousBucket ] = armRotation; //value of servo is arm rotaion
 	if( armRotation < 0 )                         // b
 		armRotation = 0;
 	if( armRotation > 255 )
 		armRotation = 255;
  wait1Msec(1);
}

// Move Flag Function
void moveFlag()
{
	if( joy1Btn( buttonLT ) )
		servo[ FlagRaiser ] = 256; 	// move flag raiser counterclockwise
	else if( joy1Btn( buttonLB ) )
		servo[ FlagRaiser ] = 0; // move flag raiser clockwise
	else
  	servo[ FlagRaiser ] = 127;
 	wait1Msec(1);
 	if( joy1Btn( buttonX ) )
		servo[ Raiser ] = 256; // move flag raiser up
	else if( joy1Btn( buttonY ) )
		servo[ Raiser ] = 0; // move flag raiser down
	else
		servo[ Raiser ] = 127;
 	wait1Msec(1);
}

//Initialize Robot Function
void initializeRobot()
{
	bFloatDuringInactiveMotorPWM   = false;
	servoChangeRate[ servoAutonomousBucket ] = 0;
}
//Move Lift Function
void moveLift()
{
	if ( ( joystick.joy2_y1 > -5 && joystick.joy2_y1 < 5 ) && ( joystick.joy2_y2 > -5 && joystick.joy2_y2 < 5 ) )
	{
		 motor[ motorLift ] = 0;
	   motor[ motorLift2 ] = 0;
	}
	else
	{
		motor[ motorLift ] = ( joystick.joy2_y2 );
		motor[ motorLift2 ] = ( joystick.joy2_y1 );
		wait1Msec(1);
	}
}

	/*
	if( joy2Btn( buttonA ) )
		servo[ servoLock ] = 0;
  else if( joy2Btn( buttonB ) )
		servo[ servoLock ] = 256;
	else
		servo[ servoLock ] = 127;
		wait1Msec(1);
	*/
