#pragma config(Motor,  motorA,          motorL,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorBack,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          motorR,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

const int buttonRt = 7;
const int buttonLt = 8;
float acceleration = 0;
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  while( true )
  {
  	getJoystickSettings( joystick );
 	  if ( joystick.joy1_x1 > 50 )
 	  {
 	  	motor[ motorA ] = 0;
			motor[ motorB ] = acceleration;
			motor[ motorC ] = acceleration;
		}
 	  else if ( joystick.joy1_x1 < -50 )
 	  {
			motor[ motorA ] = acceleration;
			motor[ motorB ] = acceleration;
			motor[ motorC ] = 0;
		}
 	 else
 	 {
 	   	motor[ motorA ] = acceleration;
			motor[ motorB ] = acceleration;
			motor[ motorC ] = acceleration;
	 }

 	  if ( joy1Btn( buttonRt ) )
			acceleration += .1;
		else if ( joy1Btn( buttonLt ) )
			acceleration -= .1;
  	else
			acceleration = 0;

			wait1Msec(1);
  }
}
