#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoBucket,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Dillon & Chase & Will & Walsh(GOD)
//10/29/13
//TeleOp

////////////////////////////////////////////////////////////////////

#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

void moveMainArm();
void moveFlag();
void moveBucketPosition();

const int buttonX  = 1;
const int buttonA  = 2;
const int buttonB  = 3;
const int buttonY  = 4;
const int buttonLB = 5;
const int buttonRB = 6;
const int buttonLT = 7;
const int buttonRT = 8;
const int armRotation = 80;
const int flagRotation = 127;
const int armMin = 255;
const int armMax = 0;
const int armHalf = 127;
const int armGround = 153;

////////////////////////////////////////////////////

task main()
{
	bFloatDuringInactiveMotorPWM = false;
	servoChangeRate[ servoBucket ] = 0;
	servo[ servoBucket ] = armMin; // all the way down

	while( true )
	{
  	getJoystickSettings( joystick );
 	  motor[ motorL ] 		= joystick.joy1_y2;
  	motor[ motorR ] 		= joystick.joy1_y1;
  	motor[ motorArm1 ] 	= joystick.joy2_y1;

  	moveMainArm();
  	moveFlag();
  	moveBucketPosition();
	}
}

//Functions
//////////////////////////////////////////////////////////////

void moveMainArm()
{
	if( joy1Btn( buttonLT ) ) //main arm
  	motor[ motorArm1 ] = armRotation;
 	else if( joy1Btn( buttonLB ) )
  	motor[ motorArm1 ] = -armRotation/2;
  else
  	motor[ motorArm1 ] = 0;

  wait1Msec(1);
}
void moveFlag()
{
	if( joy1Btn( buttonRT ) ) //flag raiser
		motor[ motorFlag ] = flagRotation;
	else if( joy1Btn( buttonRB ) )
		motor[ motorFlag ] = -flagRotation;
	else
  	motor[ motorFlag ] = 0;

 	wait1Msec(1);
}
void moveBucketPosition() //bucket
{
	if( joy1Btn( buttonX ) )
		servo[ servoBucket ] = armMin; //starting
	else if( joy1Btn( buttonA ) )
		servo[ servoBucket ] = armHalf; //driving
	else if( joy1Btn( buttonB ) )
		servo[ servoBucket ] = armMax; //dumping
	else if( joy1Btn( buttonY ) )
		servo[ servoBucket ] = armGround; //collecting

	wait1Msec(1);
}
