#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm1,     tmotorTetrix, openLoop)
#include "JoystickDriver.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Dillon & Chase
//10/4/13
//Practice Programming - circle

/*
	integers
	-intialized : int name = 0;
	ex: 0, 1, -1

	doubles aka decimals
	-intialized : double name = 0.0;
	ex: .1, 34.9, 34.0
*/
////////////////////////////////////////////////////////////////////

// Functions

void RobotTurnLeft(int speed)
{
	motor[motorR] = speed; //-
	motor[motorL] = speed;
}

void RobotTurnRight(int speed)
{
	motor[motorR] = -speed; //+
	motor[motorL] = -speed;
}

void RobotMoveForward(int speed)
{
	motor[motorR] = -speed; //+
	motor[motorL] = speed;
}

void RobotMoveBackward(int speed)
{
	motor[motorR] = speed; //-
	motor[motorL] = -speed;
}

void KILLROBOT()
{
	motor[motorR] = 0;
	motor[motorL] = 0;
}
////////////////////////////////////////////////////////////////////
task main()
{
	int num = 0;

	while(num >= 0)
	{
  RobotMoveForward(50);
  wait1Msec(500);

  RobotTurnRight(50);
  wait1Msec(1000);

  num ++;
	}
  KILLROBOT();
  }
