#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Dillon & Chase & Will
//10/31/13
//Left Ramp Autonomous

////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"

void RobotTurnLeft( int speed );
void RobotTurnRight( int speed );
void RobotMoveForward( int speed );
void RobotMoveBackward( int speed );
void StopRobot();

////////////////////////////////////////////////////////////////////
task main()
{
	RobotMoveForward( 50 ); //move away from wall
	wait1Msec( 500 );

	RobotTurnLeft( 50 ); //turn 45* Left
	wait1Msec( 500 );

	RobotMoveForward( 50 ); //move forward till lined up with ramp
	wait1Msec( 500 );

	RobotTurnRight( 50 ); //turn 90* Right
	wait1Msec( 1000 );

	RobotMoveForward( 50 ); //move forward till on ramp
	wait1Msec( 1100 );

	StopRobot();
}

// Functions
////////////////////////////////////////////////////////////////////

void RobotTurnLeft( int speed )
{
	motor[ motorR ] = -speed;
	motor[ motorL ] = speed;
}

void RobotTurnRight( int speed )
{
	motor[ motorR ] = speed;
	motor[ motorL ] = -speed;
}

void RobotMoveForward( int speed )
{
	motor[ motorR ] = speed;
	motor[ motorL ] = speed;
}

void RobotMoveBackward( int speed )
{
	motor[ motorR ] = -speed;
	motor[ motorL ] = -speed;
}

void StopRobot()
{
	motor[ motorR ] = 0;
	motor[ motorL ] = 0;
}
