#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorArm,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Dillon & Chase & Will
//10/31/13
//Block Autonomous

////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"

void RobotTurnLeft( int speed );
void RobotTurnRight( int speed );
void RobotMoveForward( int speed );
void RobotMoveBackward( int speed );
void StopRobot();

////////////////////////////////////////////////////////////////////
task main()
{
RobotMoveBackward( 50 ); //move toward basket
wait1Msec( 850 );

StopRobot(); //stop in front of basket

motor[ motorArm ] = 80; //drop block in basket block
wait1Msec( 500 );

motor[ motorArm ] = 0;

StopRobot();
}

// Functions
////////////////////////////////////////////////////////////////////

void RobotTurnLeft( int speed )
{
	motor[ motorR ] = -speed;
	motor[ motorL ] = speed;
}

void RobotTurnRight( int speed )
{
	motor[ motorR ] = speed;
	motor[ motorL ] = -speed;
}

void RobotMoveForward( int speed )
{
	motor[ motorR ] = speed;
	motor[ motorL ] = speed;
}

void RobotMoveBackward( int speed )
{
	motor[ motorR ] = -speed;
	motor[ motorL ] = -speed;
}

void StopRobot()
{
	motor[ motorR ] = 0;
	motor[ motorL ] = 0;
}
