#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoIRbucket,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    sonarServo,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(SrvoPosition,  Position01,            128, 127, 128, 128, 128, 128, 128, 128)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

const int SONARSERVOCENTERPOSITION = 117;
const int START = 78;
const int STOP = 156;
const int TRAVELDIST = STOP - START;
int correctIncrement;
int sonarValue[TRAVELDIST/3];
int lowestValue;
int ticks = 0;

void sonarSweep();
void readValues();
void initializeRobot()

{
	servo[servo1] = 40;
	servo[sonarServo] = START;
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

task main()
{
  initializeRobot();

  //waitForStart(); // Wait for the beginning of autonomous phase.



	//servo[sonarServo] = tickPosition;=
  	wait1Msec(1000);
  	sonarSweep();
  	wait1Msec(1);
  	readValues();
  	wait1Msec(1);
  	int servoLowestPosition =(correctIncrement + 1 + ticks / 2 ) * 3 + START;
  	servo[sonarServo] = (int) servoLowestPosition;
  	wait1Msec(1000);
  	/*sonar = SensorValue[sonarSensor];

  	if( sonar < 50 && sonar > 25 )
		{
			motor[motorR] = 	-10;
			motor[motorL] =   -10;
	  }
	 else
	 {
	 		motor[motorR] = 	0;
	 		motor[motorL] = 	0;
	 }*/

}
void sonarSweep()
{
	int tempSonarValue;
	int increment = 0;
	for(int i = START; i < STOP ;i+=3)
	{
		tempSonarValue = 250;
		servo[sonarServo] = i;
		for(int x = 0; x < 5; x++)
		{
			if ( SensorValue[sonarSensor] < tempSonarValue )
			{
					tempSonarValue = SensorValue[sonarSensor];
			}
			wait1Msec(35);
		}
		sonarValue[increment] = tempSonarValue;
		increment++;
		/*if(SensorValue[sonarSensor] < lowestValue)
		{
			if (SensorValue[sonarSensor] < (20 + lowestValue) && SensorValue[sonarSensor]  > (lowestValue - 20) && SensorValue[sonarSensor] < 250)
			{
				ticks++;
				lowestValue 	= SensorValue[sonarSens
			}
			else if(SensorValue[sonarServo] < lowestValue)
			{or];
				tickPosition 	= ServoValue[sonarServo];
			}

			tickPosition  += ticks/2;
		}*/
		//wait10Msec(20);
	}
/*	for(int i = STOP; i > START ;i--)
	{
		int ticks =0;
		servo[sonarServo] = i;
		if(SensorValue[sonarSensor] < lowestValue)
		{
			if (SensorValue[sonarSensor] < (20 + lowestValue) && SensorValue[sonarSensor]  > (lowestValue - 20) && SensorValue[sonarSensor] <250)
			{
				ticks++;
			}
			else if(SensorValue[sonarServo] < lowestValue)
			{
				lowestValue 	= SensorValue[sonarSensor];
				tickPosition 	= ServoValue[sonarServo];
			}

			tickposition  -= ticks/2;
		}
		wait10Msec(1);
	}*/

	//servo[sonarServo] = SONARSERVOCENTERPOSITION;
	//return (90.0/117) * tickPosition;
}

void readValues()
{
	lowestValue = sonarValue[0];

	for (int i = 0; i < TRAVELDIST/3; i++)
	{
		if ( sonarValue[i] < lowestValue )
		{
			lowestValue = sonarValue[i];
			correctIncrement = i;
			ticks = 0;
		}
		else if ( sonarValue[i] == lowestValue)
		{
			ticks++;
		}
	}
}
