#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoIRbucket,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    sonarServo,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(SrvoPosition,  Position01,            128, 127, 128, 128, 128, 128, 128, 128)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

const int SONARSERVOCENTERPOSITION = 117;
int lowestValue = 255;
int tickPosition;

int sonarSweep();

void initializeRobot()
{
	servo[servo1] = 250;
	servo[sonarServo] = SONARSERVOCENTERPOSITION;
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  //waitForStart(); // Wait for the beginning of autonomous phase.
  int sonar;
  for(int i =0; i < 3;i++)
  {
  	sonarSweep();
	}
	servo[sonarServo] = tickPosition;

  while (true)
  {
  	/*sonar = SensorValue[sonarSensor];

  	if( sonar < 50 && sonar > 25 )
		{
			motor[motorR] = 	-10;
			motor[motorL] =   -10;
	  }
	 else
	 {
	 		motor[motorR] = 	0;
	 		motor[motorL] = 	0;
	 }*/
  }
}
int sonarSweep()
{
	const int START = 58;
	const int STOP = 175;

	for(int i = START; i < STOP ;i++)
	{
		servo[sonarServo] = i;
		int ticks = 0;

		if(SensorValue[sonarSensor] < lowestValue)
		{
			if (SensorValue[sonarSensor] < (20 + lowestValue) && SensorValue[sonarSensor]  > (lowestValue - 20) && SensorValue[sonarSensor] < 250)
			{
				ticks++;
			}
			else if(SensorValue[sonarServo] < lowestValue)
			{
				lowestValue 	= SensorValue[sonarSensor];
				tickPosition 	= ServoValue[sonarServo];
			}

			tickposition  += ticks/2;
		}
		wait10Msec(1);
	}
	for(int i = STOP; i > START ;i--)
	{
		int ticks =0;
		servo[sonarServo] = i;
		if(SensorValue[sonarSensor] < lowestValue)
		{
			if (SensorValue[sonarSensor] < (20 + lowestValue) && SensorValue[sonarSensor]  > (lowestValue - 20) && SensorValue[sonarSensor] <250)
			{
				ticks++;
			}
			else if(SensorValue[sonarServo] < lowestValue)
			{
				lowestValue 	= SensorValue[sonarSensor];
				tickPosition 	= ServoValue[sonarServo];
			}

			tickposition  -= ticks/2;
		}
		wait10Msec(1);
	}

	//servo[sonarServo] = SONARSERVOCENTERPOSITION;
	return (90.0/117) * tickPosition;
}
