#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoIRbucket,        tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    sonarServo,           tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(SrvoPosition,  Position01,            128, 127, 128, 128, 128, 128, 128, 128)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

const int SONARSERVOCENTERPOSITION = 117;
const int START = 78;
const int STOP = 158;
const int TRAVELDIST = STOP - START;
const int ONEROTATION = 1410;
const int QUARTERTURNATHALFPOWER = 2100;
const int overEncoderAmount = 2000; //
const int CIRCUMFERENCEOFWHEEL = 31.9;
const float encoderTicksPerCentimeters =  ONEROTATION / CIRCUMFERENCEOFWHEEL;



typedef struct SonarDataStruct
{
	int servoPosition;
	int detectionTicks; //.769 degrees per tick
	int sonarDistance;
}SonarData;

void turnRight(int degree);
void turnLeft( int degree );
void goForward( int distance );
void sonarSweep(int* array);
void readValues(int* array,SonarData *calculatedValues);
void turnToObject(int servoPosition);
void scanAndTurn(SonarData* calculatedValues);
void initializeRobot()

{
	servo[servo1] = 250;
	servo[sonarServo] = START;

}

task main()
{
  initializeRobot();
	//waitForStart(); // Wait for the beginning of autonomous phase.

	SonarData calculatedValues;

		goForward(200);
	//servo[sonarServo] = tickPosition;
		scanAndTurn(calculatedValues);
		scanAndTurn(calculatedValues);

  	goForward(calculatedValues.sonarDistance/4);

  	scanAndTurn(calculatedValues);
  	scanAndTurn(calculatedValues);
  	goForward(calculatedValues.sonarDistance/4);
  	scanAndTurn(calculatedValues);

  	/*sonar = SensorValue[sonarSensor];

  	if( sonar < 50 && sonar > 25 )
		{
			motor[motorR] = 	-10;
			motor[motorL] =   -10;
	  }
	 else
	 {
	 		motor[motorR] = 	0;
	 		motor[motorL] = 	0;
	 }*/

}
void sonarSweep(int* array)
{

	int tempSonarValue;
	int increment = 0;

	for(int i = START; i < STOP ;i+=3)
	{
		tempSonarValue = 250;
		servo[sonarServo] = i;
		for(int x = 0; x < 5; x++)
		{
			if ( SensorValue[sonarSensor] < tempSonarValue )
			{
					tempSonarValue = SensorValue[sonarSensor];
			}
			wait1Msec(35);
		}
		array[increment] = tempSonarValue;			//Assign values to array
		increment++;
	}
}

void readValues(int* array,SonarData *calculatedValues)
{
	calculatedValues->sonarDistance = array[0];

	for (int i = 0; i < TRAVELDIST/3; i++)
	{
		if ( array[i] < calculatedValues->sonarDistance )
		{
			calculatedValues->sonarDistance = array[i];
			calculatedValues->servoPosition = i;
			calculatedValues->detectionTicks = 0;
		}
		else if ( array[i] == calculatedValues->sonarDistance)
		{
			calculatedValues->detectionTicks++;
		}
	}
}

void goForward( int distance ) //centimeters
{
	int encoderTicksNeeded = -( distance * encoderTicksPerCentimeters );
	nMotorEncoder[ driveLeft ] = 0;
  nMotorEncoder[ driveRight ] = 0;
  int hiSpeedTicks = encoderTicksNeeded + overEncoderAmount;

 	while( nMotorEncoder[ driveLeft ] > hiSpeedTicks && nMotorEncoder[ driveRight ] > hiSpeedTicks )
	{
		motor[ driveLeft ] = 50;
  	motor[ driveRight ] = 50;
	}
// motor[ driveLeft ] = 0;
// motor[ driveRight ] = 0;
// wait1Msec( 1000 );
	while( nMotorEncoder[ driveLeft ] > encoderTicksNeeded && nMotorEncoder[ driveRight ] > encoderTicksNeeded )
	{
		motor[ driveLeft ] = 10;
		motor[ driveRight ] = 10;
	}
	motor[ driveLeft ] = 0;
	motor[ driveRight ] = 0;
}

void turnRight(int degree )
{
	nMotorEncoder[ driveLeft ] = 0;
  nMotorEncoder[ driveRight ] = 0;
  int encoderAmount = QUARTERTURNATHALFPOWER / 90 * degree;
  while( nMotorEncoder[ driveLeft ] > -encoderAmount && nMotorEncoder[ driveRight ] > -encoderAmount )
	{
		motor[ driveLeft ] = 50;
		motor[ driveRight ] = -50;
	}
	motor[ driveLeft ] = 0;
	motor[ driveRight ] = 0;
}

void turnLeft( int degree )
{
	nMotorEncoder[ driveLeft ] = 0;
  nMotorEncoder[ driveRight ] = 0;
  int encoderAmount = QUARTERTURNATHALFPOWER / 90 * degree;

  //Turn
  while( nMotorEncoder[ driveLeft ] > -encoderAmount && nMotorEncoder[ driveRight ] > -encoderAmount )
	{
		motor[ driveLeft ] = -50;
		motor[ driveRight ] = 50;
	}

	//Stop robot
	motor[ driveLeft ] = 0;
	motor[ driveRight ] = 0;
}


void turnToObject(int servoPosition)
{
	if( servoPosition < 117 )
	{
		turnLeft((SONARSERVOCENTERPOSITION - servoPosition ) * .769);
	}
	else
	{
		turnRight((servoPosition - SONARSERVOCENTERPOSITION) * .769);
	}
}
void scanAndTurn(SonarData* calculatedValues)
{
		int servoTargetPosition;
  	int sonarValue[TRAVELDIST/3];

	  wait1Msec(1000);
  	sonarSweep(sonarValue);
  	wait1Msec(1);
  	readValues(sonarValue, calculatedValues);
  	wait1Msec(1);
  	servoTargetPosition =(calculatedValues->servoPosition + 1 + calculatedValues->detectionTicks / 2 ) * 3 + START;
  	turnToObject(servoTargetPosition);

  	servo[sonarServo] = SONARSERVOCENTERPOSITION;
}
