#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBelt,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoStopper,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma debuggerWindows("joystickGame");
#include "JoystickDriver.c"
const int buttonX  			= 1;
const int buttonA 		  = 2;
const int buttonB       = 3;
//const int buttonY  			= 4;
//const int buttonLB 			= 5;
const int buttonRB 			= 6;
//const int buttonLT 			= 7;
const int buttonRT 			= 8;

//void runConveyer();
void runStopper();
//void runLift();


task main()
{
	while( true )
	{
		getJoystickSettings( joystick );
 	  motor[ motorL ] 		= joystick.joy1_y2;
  	motor[ motorR ] 		= joystick.joy1_y1;
  	//runConveyer();
  	//runLift();
  	runStopper();
	}
}
/*
void runConveyer()
{
	if ( joy1Btn( buttonB ) )
	{
		motor[ motorBelt ] = 50;
		wait1Msec(1);
	}
	else
	{
		motor[ motorBelt ] = 0;
		wait1Msec(1);
	}
}
*/
/*void runLift()
{
	if ( joy1Btn( buttonRT ) )
	{
		motor[ motorLift ] = 50;
		wait1Msec(1);
	}
	else if ( joy1Btn( buttonRB ) )
	{
		motor[ motorLift ] = -50;
		wait1Msec(1);
	}
	else {
		motor[ motorLift ] = 0;
		wait1Msec(1);
	}
}
*/
void runStopper()
{
	if ( joy1Btn( buttonA ) )
	{
		servo[ servoStopper ] = 240;
		wait1Msec(1);
	}
	else if ( joy1Btn( buttonX ) )
	{
		servo[ servoStopper ] = 120;
		wait1Msec(1);
	}
}
